version: "3.9"

networks:
  mynetwork:
    name: mynetwork
    driver: bridge

services:
  database:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    env_file: .env
    volumes:
      - D:\\posthre:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_PORT=$POSTGRES_PORT
      - POSTGRES_HOST=$POSTGRES_HOST
    networks:
      - mynetwork
      
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    image: url-shortener_app
    container_name: app
    ports:
      - 3000:3000
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_PORT=$POSTGRES_PORT
      - POSTGRES_HOST=$POSTGRES_HOST
    depends_on:
      - database
    restart: unless-stopped
    env_file: .env
    volumes:
      - .:/home/node/app
    networks:
      - mynetwork
      